### PR TITLE
Revert PR#3663

### LINKED ISSUE #2884: Repeated column when use encrypt with JPA + Springboot
### Which version of ShardingSphere did you use?

4.0.0-RC2-SNAPSHOT

### Which project did you use? Sharding-JDBC or Sharding-Proxy?

Sharding-JDBC

### Expected behavior

Insert encrypt successfully.

### Actual behavior

```
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Column 'user_name_plain' specified twice
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.Util.getInstance(Util.java:408)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:943)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2490)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2079)
	at com.mysql.jdbc.PreparedStatement.executeUpdateInternal(PreparedStatement.java:2013)
	at com.mysql.jdbc.PreparedStatement.executeLargeUpdate(PreparedStatement.java:5104)
	at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:1998)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.apache.shardingsphere.shardingjdbc.jdbc.core.statement.EncryptPreparedStatement.executeUpdate(EncryptPreparedStatement.java:120)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:208)
	... 23 more
```

### Reason analyze (If you can)

Logic SQL: `insert into t_user (assisted_query_pwd, pwd, user_name, user_name_plain, user_id) values (?, ?, ?, ?, ?)`

actual SQL: `insert into t_user (assisted_query_pwd, pwd, user_name, user_name_plain, user_id, assisted_query_pwd, user_name_plain) values (?, ?, ?, ?, ?, ?, ?) `

SQL generated by JPA has included `user_name_plain `, but encrypt add `user_name_plain` again.

### Steps to reproduce the behavior, such as: SQL to execute, sharding rule configuration, when exception occur etc.

clone example code.
run `sharding-jdbc-example/other-feature-example/encrypt-example/encrypt-spring-boot-example/src/main/java/org/apache/shardingsphere/example/encrypt/table/spring/boot/SpringBootExample.java`

### Example codes for reproduce this issue (such as a github link).

https://github.com/apache/incubator-shardingsphere-example

### PR DESCRIPTION
**Pull request by KomachiSion**
Revert reason, the PR causes the new issue #3770 .
I think we need to revert and use DDL of encrypt to fix #2884 .

### CODE REVIEW

**Comment by KomachiSion** [comment]
HI @xiyelife , After the PR merged, there are some error for you added in #3768 .

Can you update the test case so that it can run correctly?

**Comment by tristaZero** [comment]
@xiyelife Hi boy, we need your support. This issue blocks our coming release!

This PR rollbacks one commit to solve #3770 , however one unit test in (your PR)[https://github.com/apache/incubator-shardingsphere/pull/3768] can not run well.
Currenty we have to ignore this unit test, so could you give a look at it and make it run well again?
Looking forward to your reply, Thx.

**Comment by xiyelife** [comment]
@tristaZero  yeah, I can make  my pr https://github.com/apache/incubator-shardingsphere/pull/3768 run well, but how to do it with this revert PR and waiting for it has been merged to dev , then submit a new PR?

**Comment by KomachiSion** [comment]
> @tristaZero yeah, I can make my pr #3768 run well, but how to do it with this revert PR and waiting for it has been merged to dev , then submit a new PR?

Yes, after this pr merged, init table SQL `INSERT INTO t_encrypt_contains_column VALUES(1, 'cipherValue', 'plainValue', 'cipherValue', 'plainValue')` will execute error.

**Comment by xiyelife** [comment]
@KomachiSion when your revert PR is merged, I'll sumbit a new PR to fixed it and add my unit test back.

**Comment by KomachiSion** [comment]
> @KomachiSion when your revert PR is merged, I'll sumbit a new PR to fixed it and add my unit test back.

Thanks.

**Comment by tristaZero** [comment]
@xiyelife Hi so now It’s your turn. :）

**Comment by tristaZero** [comment]
@xiyelife Hi sir, i notice that you have do a few of contributions to shardingsphere community. Very appreciated your effort. 

Just out of my curiosity, do you enjoy it and also want to do more to this community? From my side, you are energetic and have a bit clear understand of sharding sphere. So i am expecting your successive interactions in sharding sphere community and to be our  committer one day. Good luck and welcome!

**Pull request merged**
