### PR TITLE
add Java Microbenchmark Harness

### PR DESCRIPTION
**Pull request by CalvinKirs**
Fixes #ISSUSE_ID.
#2746 
Changes proposed in this pull request:
-
-add Java Microbenchmark Harness
-

### CODE REVIEW

**Comment by CalvinKirs** [comment]
> Can one of the admins verify this patch?
of course

**Comment by CalvinKirs** [comment]
@tristaZero can you help me review

**Comment by nancyzrh** [comment]
is there any way to run jmh compared with its last results automatically or just run as junit cases?

**Comment by CalvinKirs** [comment]
> is there any way to run jmh compared with its last results automatically or just run as junit cases?



> is there any way to run jmh compared with its last results automatically or just run as junit cases?



> is there any way to run jmh compared with its last results automatically or just run as junit cases?

Wait a moment, I will finish it.

**Comment by CalvinKirs** [comment]
> is there any way to run jmh compared with its last results automatically or just run as junit cases?

Wait a moment, I will finish it.

**Comment by nancyzrh** [comment]
> > is there any way to run jmh compared with its last results automatically or just run as junit cases?
> 
> Wait a moment, I will finish it.

good~

**Comment by CalvinKirs** [comment]
> > > is there any way to run jmh compared with its last results automatically or just run as junit cases?
> > 
> > 
> > Wait a moment, I will finish it.
> 
> good~

I think I understand what you mean wrong. This is a beautiful misunderstanding. JMH is just a quantifiable data report to reflect your code's performance. It is mainly used for our general core logic optimization code (basic code or algorithm level), and we usually use the Test package to indicate the accuracy of your code. The focus of the two is different.

**Comment by CalvinKirs** [comment]
@terrymanu Hello, can you help me review my code?

**Comment by terrymanu** [comment]
@CalvinKirs  Just as @nancyzrh said, this pr just add a maven dependency for jmh, but does not include any test cases yet, so I think you need add test cases first.

As my understanding, jmh only can print benchmark info to console which is not very make sense, we have already use jmeter to test benchmark.

The precondition for introduce jmh to ShardingSphere is we need to auto assert if benchmark is under threshold.

**Comment by CalvinKirs** [comment]
> @CalvinKirs Just as @nancyzrh said, this PR only add a maven dependency for jmh, but does not add any test cases yet, so I think you need add test cases for that.
> 
> As my understanding, jmh only can print benchmark info to console which is not very make sense, we have already use jmeter to test benchmark.
> 
> The precondition for introduce jmh to ShardingSphere is we need to auto assert if benchmark is under threshold.

I don't quite agree with your point of view. The existence is reasonable. The microcode test I think needs more lightweight JMH, not Jmeter. The level of action of the two is different. Using JMH will make our committers more convincing when submitting certain code. Of course, it may be my fault. I still want to hear your suggestions or suggestions from others.

**Comment by CalvinKirs** [comment]
> > @CalvinKirs Just as @nancyzrh said, this PR only add a maven dependency for jmh, but does not add any test cases yet, so I think you need add test cases for that.
> > As my understanding, jmh only can print benchmark info to console which is not very make sense, we have already use jmeter to test benchmark.
> > The precondition for introduce jmh to ShardingSphere is we need to auto assert if benchmark is under threshold.
> 
> I don't quite agree with your point of view. The existence is reasonable. The microcode test I think needs more lightweight JMH, not Jmeter. The level of action of the two is different. Using JMH will make our committers more convincing when submitting certain code. Of course, it may be my fault. I still want to hear your suggestions or suggestions from others.

It is absolutely necessary to use Jmeter for large-scale stress testing, which allows us to implement the project with data results as a support. But the microcode test uses Jmeter just like Take not a musket to kill a butterfly.

**Comment by terrymanu** [comment]
Can jmh auto assert if benchmark under threshold?

**Comment by CalvinKirs** [comment]
> Unit tests need assert automatically, otherwise nobody will notice performance is slow at the moment.
> 
> Can jmh auto assert if benchmark under threshold?

of course

**Comment by terrymanu** [comment]
How to do it, could you add more jmh test case on this pr?

**Comment by CalvinKirs** [comment]
> How to do it, could you add more jmh test cases on this pr?

Sorry, I am busy recently, I will finish it later.

**Comment by terrymanu** [comment]
@CalvinKirs Hi, it is not a good practice to close pull request without any reason.
Can you explain the reason?

**Comment by CalvinKirs** [comment]
> @CalvinKirs Hi, it is not a good practice to close pull request without any reason.
> Can you explain the reason?

So sorry, my understanding has a deviation，so this may be a wrong decision

**Pull request closed without merging**
