### PR TITLE
Add leaf segment key generator related functions.

### LINKED ISSUE #1775: Leaf key generator implementation for Apache ShardingSphere
Modifying API of generating gobally unique ID, and providing alternatives of gobally unique ID generator for users now is ongoing.

To meet users' different needs and make the module of globally unique ID key generator more powerful, we plan to implement Leaf key generator for ShardingSphere.

Welcome [@Zhaodong Xie](https://github.com/Yaccc), the author of Leaf, to contribute to Apache ShardingSphere. He will be in charge of Leaf key generator implementation for Apache ShardingSphere.

[1] https://tech.meituan.com/MT_Leaf.html

### PR DESCRIPTION
**Pull request by wgy8283335**
Fixes #1775.

Changes proposed in this pull request:
- Add new key generator "LeafSegmentKeyGenerator" and related functions.
-
-

### CODE REVIEW

**Comment by wgy8283335** [comment]
@tristaZero.

**Comment by terrymanu** [comment]
Any relationship with #2449

**Comment by wgy8283335** [comment]
@terrymanu. This is a new implementation of the leaf segment key generator. #2449 is old and will be 
redundant.

**Comment by terrymanu** [comment]
So maybe you can close #2449

**Comment by wgy8283335** [comment]
@terrymanu. I've closed it.

**Comment by tristaZero** [comment]
@wgy8283335 Hi, i think the new pr is better and clearer. Maybe we can have a discussion on two of optimization terms.
1. The configurations of regsitry, in which we can find required items and optional items. For required items, we need to check them when initializing LeafGenerator e.g, serverLists, TYPE, namespace.
2. Can LeafGenerator use other registry center e.g, ETCD?

**Comment by tristaZero** [comment]
@wgy8283335 Hi, i think the new pr is better and clearer. Maybe we can have a discussion on two of optimization terms.
1. The configurations of regsitry, in which we can find required items and optional items. For required items, we need to check them when initializing LeafGenerator e.g, serverLists, TYPE, namespace.
2. Can LeafGenerator use other registry center e.g, ETCD?

**Comment by wgy8283335** [comment]
@tristaZero. The required items haven ben checked in the get***() method. For example, getServerList(),getStep().  TYPE and NAMESPACE are initialized to be static final member, the value of them won't be changed.

**Comment by wgy8283335** [comment]
@tristaZero. I made a pull request.

**Pull request merged**
