### PR TITLE
resolve resetLimitTokens removeLimitToken

### PR DESCRIPTION
**Pull request by acseed**
Fixes #ISSUSE_ID.

Changes proposed in this pull request:
- delete list from foreach is not good
-
-

### CODE REVIEW

**Comment by acseed** [comment]
fix  在foreach 按照下标删除会导致越界

**Comment by tuohai666** [comment]
1. Good idea to simplify the code, we decide to merge your pr. But the original code can not lead to a bug really, you can find out the reason by yourself.
2. Why not respond my comment before?

**Comment by acseed** [comment]
> 1. Good idea to simplify the code, we decide to merge your pr. But the original code can not lead to a bug really, you can find out the reason by yourself.
> 2. Why not respond my comment before?
>    image

> it is not just simplify the code,  the original code do lead to a bug, the "toBeRemovedIndexes"  is the index to remove,  but after sqlTokens remove the first, the index in sqlTokens is changed, this may cause java.lang.IndexOutOfBoundsException,  when select sql has subQuery, the bug occurs, you try

**Comment by acseed** [comment]
> > 1. Good idea to simplify the code, we decide to merge your pr. But the original code can not lead to a bug really, you can find out the reason by yourself.
> > 2. Why not respond my comment before?
> >    image
> 
> > it is not just simplify the code,  the original code do lead to a bug, the "toBeRemovedIndexes"  is the index to remove,  but after sqlTokens remove the first, the index in sqlTokens is changed, this may cause java.lang.IndexOutOfBoundsException,  when select sql has subQuery, the bug occurs, you try

it is my fault not to respond your comment before, sorry

**Pull request merged**
