### PR TITLE
fix issue #1770

### LINKED ISSUE #1770: A sharded table into two Oracle database datasource got different TableMetaData!
## Bug Report

[please click this link for bug report!](https://www.zybuluo.com/survivorZzz/note/1392056)

Asking for your reply! thank you !

### PR DESCRIPTION
**Pull request by sixianli**
Fixes #1770 .

### CODE REVIEW

**Comment by tuohai666** [comment]
I catch you. I work on your pr that late, and can't understand. Please contact me, this pr should be merged today.

**Comment by tuohai666** [comment]
@sixianli Would you like to join our WeChat Group?

**Comment by tuohai666** [comment]
1755 is ok to me. Could you explain 1770?

**Comment by sixianli** [comment]
@tuohai666 about the #1770 , in the tag 3.0.0 version, in oracle database, the same table structure in different datasource got dirrerent TableMetaData objects. I debugged and found that List<ColumnMetaData> object of each TableMetaData is different , each List<ColumnMetaData> object contains repetitive columnMetaData objects, so i add a little filter logic code.

**Comment by tuohai666** [comment]
> @tuohai666 about the #1770 , in the tag 3.0.0 version, in oracle database, the same table structure in different datasource got dirrerent TableMetaData objects. I debugged and found that List object of each TableMetaData is different , each List object contains repetitive columnMetaData objects, so i add a little filter logic code.

Could you now contact me with IM ?

**Comment by sixianli** [comment]
@tuohai666 yes , i can , i am a little shy, I hope you don't mind.

**Comment by sixianli** [comment]
i am a new guy about opensource in github and could you please tell me how to you the IM ?

**Comment by tuohai666** [comment]
> @tuohai666 yes , i can , i am a little shy, I hope you don't mind.

It's OK. My wechat number: 15810310987. I'll pull you to ShardingSphere WeChat Group. We discuss publicly there.

**Comment by sixianli** [comment]
ok! thank you then!

**Pull request merged**
