### PR TITLE
#2126 add SQLLoggerTest

### LINKED ISSUE #2126: SQLLogger should have a junit test
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?
No.
### Describe the feature you would like.
SQLLogger should have a junit test.

### PR DESCRIPTION
**Pull request by betterjava**
Fixes #2126 .

Changes proposed in this pull request:
-add SQLLoggerTest to test SQLLogger

### CODE REVIEW

**Comment by betterjava** [comment]
@terrymanu can you help me to  review my pull ?

**Comment by terrymanu** [comment]
The idea of mock test is good. Cloud you use checkstyle to check your code and fix waring of your code?

**Comment by terrymanu** [comment]
FYI: https://shardingsphere.apache.org/community/en/contribute/code-conduct/

**Comment by betterjava** [comment]
OK,I have used checkstyle,but seems not work fo Test class.I will check.

**Comment by betterjava** [comment]
I am sorry to set the wrong property for checkstyle. I have checked the code with the correct checkstyle config.

**Comment by terrymanu** [comment]
That's prefect, I will merge them

**Pull request merged**
