### PR TITLE
#1818 add sql.simple to sharding config

### LINKED ISSUE #1818: when the Logic SQL is very long, SQLLogger print too much. if the Logic SQL is Cross-sharding，that's worse
## Feature Request

when the Logic SQL is very long, SQLLogger print too much. if the Logic SQL is Cross-sharding，that's worse：
if there are 128 sharding table，there are 128 Actual SQL .
and SQLStatement and Logic SQL also will Output thousands of lines .

These outputs are of little value. So suggest that add a configuration(for example: **sharding.jdbc.config.props.sql.show.simple=true**) to simple it.

### PR DESCRIPTION
**Pull request by betterjava**
Fixes #1818 .

Changes proposed in this pull request:
- add sql.simple to sharding config.
- if this properties is true,in shard module,log will display in sample style.

### CODE REVIEW

**Comment by terrymanu** [comment]
Thank you for contribute codes.
The code is good, I just merge it.

**Comment by terrymanu** [comment]
I do some refactor for this pr:
`d36d3026f8e66cb2c326905a42693a6ee0cbd691` for code format.
`660a570565aafc0691575964371da16857ada317` to extract smaller method.

if you have time, may review them.

**Comment by terrymanu** [comment]
@betterjava By the way, class `SQLLogger` do not have test case, do you interested add them.
If interested, we can discuss how to mock log variable and verify log content.

**Comment by betterjava** [comment]
Ok,  I am glad to do so. I will try my best to figure out how to test  Logger. I am so excited  for my first code pull request have been merged.hahaha , I will take part in open source more positive in the future.

**Comment by terrymanu** [comment]
Congratulations to be a contributor.
For more info about mock, you can reference of: `org.apache.shardingsphere.shardingproxy.transport.mysql.packet.generic.MySQLEofPacketTest`

**Pull request merged**
