### PR TITLE
Fixes #2629

### LINKED ISSUE #2629: Get NullPointerException when execute SQL on tables without sharding rule
## Bug Report

**For English only**, other languages will not accept.

Before report a bug, make sure you have:

- Searched open and closed [GitHub issues](https://github.com/apache/incubator-shardingsphere-example/issues).
- Read documentation: [ShardingSphere Doc](https://shardingsphere.apache.org/document/current/en/overview).

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot reproduce it on current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Which project did you use? Sharding-JDBC or Sharding-Proxy?
Sharding-JDBC and Sharding-Proxy
### Expected behavior
Get Sharding Execption when execute SQL on tables without sharding rule
### Actual behavior
Get NullPointerException when execute SQL on tables without sharding rule
### Reason analyze (If you can)
Parse engine will parse tableName, Route engine pass the SQLStatement to UnicastRoutingEngine, which return RoutingResult with null datasource name.
Ref:
```
RoutingEngineFactory.java
if (shardingRule.isAllBroadcastTables(tableNames)) {
            return sqlStatement instanceof SelectStatement ? new UnicastRoutingEngine(shardingRule, tableNames) : new DatabaseBroadcastRoutingEngine(shardingRule);
        }

ShardingDataSourceNames.java
public String getDefaultDataSourceName() {
        return 1 == dataSourceNames.size() ? dataSourceNames.iterator().next() : shardingRuleConfig.getDefaultDataSourceName();
    }
```

### PR DESCRIPTION
**Pull request by sunbufu**
Changes proposed in this pull request:
- throw `ShardingException` when execute `RoutingEngine.newInstance()` with null `ShardingRule`
- avoid NPE when execute `ShardingDataSourceNames.getDefaultDataSourceName()` with null `shardingRuleConfig`

Hello, this is my first PR for `shardingsphere`. so If I do something wrong, please let me know. Thank U.

### CODE REVIEW

**Comment by sunbufu** [comment]
https://github.com/apache/incubator-shardingsphere/issues/2629

**Comment by tristaZero** [comment]
Hi, thanks for your pr.
In your pr, you said that if there is no shardingRule, `RoutingEngine.newInstance()` and `RoutingEngine.newInstance()` will throw NPE. But when will the shardingRule be null? Because if you want to sharding tables, shardingRule is necessary, otherwise you can not start up.
Can u give me some scenerios?

**Comment by sunbufu** [comment]
> Hi, thanks for your pr.
> In your pr, you said that if there is no shardingRule, `RoutingEngine.newInstance()` and `RoutingEngine.newInstance()` will throw NPE. But when will the shardingRule be null? Because if you want to sharding tables, shardingRule is necessary, otherwise you can not start up.
> Can u give me some scenerios?

Thank you for reply. I agree with you, and In my view, I think `RoutingEngine.newInstance()` should throw `ShardingException` replace NPE, when `ShardingRule` is empty (include null). You can find this code on `RoutingEngineFactory` in line 68 to 70.
And, I think `ShardingDataSourceNames` is same with `RoutingEngine`. This code in lines 45 to 47 on `ShardingDataSourceNames` of my PR.

**Comment by tristaZero** [comment]
Hi, Considering user will create ShardingRule to create ShardingDataSource, i think it is better to judge whether null == shardingRuleConfig, but do you think it is better to add this judgement in ShardingRule.java?
```
public ShardingRule(final ShardingRuleConfiguration shardingRuleConfig, final Collection<String> dataSourceNames) {
        // Here just checking dataSourceNames, maybe we can add checking shardingRuleConfig?
        Preconditions.checkArgument(!.isEmpty(), "Data sources cannot be empty.");
        this.shardingRuleConfig = shardingRuleConfig;
       // If we add shardingRuleConfig checking ahead, there is no chance to enter into it.
        shardingDataSourceNames = new ShardingDataSourceNames(shardingRuleConfig, dataSourceNames);
```
Once ShardingRule, i.e, ShardingDataSource is created, it is impossible that shardingRule will be null in RoutingEngineFactory. What do you think?

**Comment by sunbufu** [comment]
You are right, ShardingRule is meaningless with a null ShardingRuleConfig. So, we need a judge in ShardingRule's constructor. and I notice there may throw a NPE in `ShardingRule.createEncryptRule()` when `shardingRuleConfig` is null. 
There is a question. Should I throw a `ShardingException` or `IllegalArgumentException` on this case? If we choose `ShardingException`, I need modify `dataSourceNames`'s judge too.

**Comment by sunbufu** [comment]
Confuse the commit log by rebase, so I send a new and close this.

**Pull request closed without merging**
