### PR TITLE
fix return decimal column with an exponent field

### PR DESCRIPTION
**Pull request by avalon566**
Changes proposed in this pull request:
- fix return decimal column with an exponent field

```
BigDecimal data = new BigDecimal(BigInteger.ZERO, 20);
System.out.println(data.toString()); // output 0E-20
System.out.println(data.toPlainString()); // output 0.00000000000000000000
```

### CODE REVIEW

**Comment by tuohai666** [comment]
Thanks for your effort. I'm thinking deeply into this pr now.
I wonder what problem have you met? Do you have a test report?

**Comment by tuohai666** [comment]
I noticed your merge branch operation, but the conflicts still exist.

I just finished a test:

There are two rows in MySQL server which values:
Row 1:     0.00000000000000000000
Row 2:     0E-20

Select from MySQL server:
0
0

Select from Sharding-Proxy:
0
0

As I asked just now, what problem have you met?

**Comment by avalon566** [comment]
a column in table define as decimal(25,20) and store value 0.when i select that column,it returns 0E-20,mysql driver can not parse it.

**Comment by tuohai666** [comment]
@avalon566 I got it.

**Pull request merged**
