### PR TITLE
Fixes #3370 .and change some code structure for compatibility

### PR DESCRIPTION
**Pull request by beijing-penguin**
Fixes #3370 .

Changes proposed in this pull request:
- use jdbc api to fix oracle difference and fix other jdbc compatibility
- Fix jdbc getIndexInfo method and NullPointerException.
- Fix and change catalog and schema method parameter error.
- Fix and change resultSet.getString(IS_NULLABLE) and
resultSet.getString(IS_AUTOINCREMENT) return type error.(at MySQL Connector/J 8.0 + not work)
- change some code structure for current compatibility

### CODE REVIEW

**Comment by beijing-penguin** [comment]
for fix ci

**Comment by tristaZero** [comment]
@beijing-penguin Hi, Chao. We are looking forward to your PR, for many issues similar with #3370 were opened, and many contributors raized their PRs to solve so far. However IMO, your solution is more complete. 
Please refer to #3539, and #2949 .

**Comment by sunft** [comment]
@tristaZero So, This issue has been solved? But I found the latest stable version still has this issue. How can I get the available jar? I have to package the fixed branch myself?

**Comment by tristaZero** [comment]
> @tristaZero So, This issue has been solved? But I found the latest stable version still has this issue. How can I get the available jar? I have to package the fixed branch myself?

Hi, could you point the issue number ? ssince this pr referred to a few issues, i could not know which issue you mentioned.

**Comment by sunft** [comment]
@tristaZero I'm sorry. I thought these issues are related. What I mentioned is issue #3446.

**Comment by tristaZero** [comment]
> @tristaZero I'm sorry. I thought these issues are related. What I mentioned is issue #3446.

@sunft Hi, you'right, our latest version does not inculde this bugfix, which exists [dev branch](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/datasource/dialect/OracleDataSourceMetaData.java).

**Comment by Fwenjie** [comment]
> > @tristaZero I'm sorry. I thought these issues are related. What I mentioned is issue #3446.
> 
> @sunft Hi, you'right, our latest version does not inculde this bugfix, which exists [dev branch](https://github.com/apache/incubator-shardingsphere/blob/dev/sharding-core/sharding-core-common/src/main/java/org/apache/shardingsphere/core/metadata/datasource/dialect/OracleDataSourceMetaData.java).

hi， how many packages should be replaced，please。
i find sharding-jdbc-core has lots of dependency packages,should every package be downloaded to replace.

**Comment by Fwenjie** [comment]
i has replaced the packages that named “sharding-core-common”，“sharding-core-api”，“shardingsphere-spi”,bug the last one "sharding-jdbc-core" has too many dependencys.

**Comment by sunft** [comment]
@tristaZero Hi, I am sorry to bother you.  But I have a problem. How can I get the fixed jar?  My coworker has downloaded the dev branch and we found it's complicated and has so many dependencies,  we have packaged many times, but we failed. What I mentioned is issue #3446.

**Comment by beijing-penguin** [comment]
@sunft  Could you provide  the compiling error information.

**Comment by Fwenjie** [comment]
@beijing-penguin Hi, I am the coworker  of sunft.
I have downloaded the jars  that named “sharding-core-common”，“sharding-core-api”，“shardingsphere-spi”,bug the last one "sharding-jdbc-core" has too many dependencys ,so I have not download,so it has errors. 
this is the error:
`Caused by: java.lang.NoClassDefFoundError: org/apache/shardingsphere/core/metadata/datasource/ShardingDataSourceMetaData`

**Comment by tristaZero** [comment]
@Fwenjie  Sorry for that, however my suggestion is to download or clone dev branch and intall **the whole project** in some development tools, such as IDEA.

**Comment by tristaZero** [comment]
@Fwenjie Did you try to command `mvn clean install -Prelease`?

**Comment by beijing-penguin** [comment]
like this :
image

**Comment by Fwenjie** [comment]
@beijing-penguin  yes, i have already tryed.,but it has  compiling error,i downloaded the zip form your github which exists dev branch.
`Error:(22, 52) java: 程序包org.apache.shardingsphere.sql.parser.autogen不存在`
image

**Comment by Fwenjie** [comment]
so install the whole  project  is failed.
4ca33aa243cbbf7225e3d568ae1760c

**Comment by Fwenjie** [comment]
@beijing-penguin 
can you give us the jars that compiled successfully

**Comment by beijing-penguin** [comment]
@Fwenjie give me your email

**Comment by Fwenjie** [comment]
@beijing-penguin 
thanks，this is my email "fangwenjie@wxchina.com"

**Comment by Fwenjie** [comment]
@beijing-penguin  Hi,I am sorry to bother you, but I have not received the jars , I am afraid of that you forget this.

**Comment by beijing-penguin** [comment]
@Fwenjie  I have send,,,you must use command "tar zxvf " to unzip the email attachment.

**Comment by Fwenjie** [comment]
@beijing-penguin  ok,thanks.

**Pull request closed without merging**
