### PR TITLE
Fixes #3770. if the logic columns are the same as the plain columns also add the plain columns and the parameters to the rewrited SQL.

### LINKED ISSUE #3770: Insert miss the plain columns in the final sql.
### Which version of ShardingSphere did you use?
4.0.0-RC4-SNAPSHOT
### Which project did you use? Sharding-JDBC or Sharding-Proxy?
sharding-jdbc
### Expected behavior
the encrypt rule config  plain column  the same to logic column can insert plain column to the db
### Actual behavior
It can not insert the plain to the db
### Reason analyze (If you can)

org.apache.shardingsphere.sql.rewriter.encrypt.token.generator.impl.AssistQueryAndPlainInsertColumnsTokenGenerator#getColumns
image
This code cause the plain column can not be the same to the logic column，ohterwise the plain column is missing.

org.apache.shardingsphere.sql.rewriter.encrypt.parameter.impl.EncryptInsertValueParameterRewriter#encryptInsertValue：
**And  miss the plain column's parameter too：**
because of the logic column is the same to the plain column，it's only add the cipher column 
 for addReplacedParameters. (the plainColumnIndex must be not -1 when the logic column is the same to plain column)
image

rule config like this , the final sql will do not contains the plain columns! 

```
encryptRule:
  tables:
    t_account_bak:
      columns:
        password:
          cipherColumn: cipher_password
          assistedQueryColumn: assisted_query_password
          plainColumn: password
          encryptor: assisted_query
  encryptors:
    normal:
      type: NORMAL_ENCRYPT
    assisted_query:
      type: ASSISTED_QUERY_ENCRYPT
```

@terrymanu

### PR DESCRIPTION
**Pull request by xiyelife**
Fixes #3770 

Changes proposed in this pull request:
- if the logic columns are the same as the plain columns also add the plain columns and the parameters to the rewrited SQL.

### CODE REVIEW

**Comment by xiyelife** [comment]
CI jenkins has OOM for Caused by: java.lang.OutOfMemoryError: unable to create new native thread
please replay my CI, thanks!

**Comment by xiyelife** [comment]
sharding-core test run failed, I'll test and modify later

**Comment by tristaZero** [comment]
@xiyelife Hi, thanks for your pr. And my review would come after CI becomes ok.

**Comment by xiyelife** [comment]
@tristaZero I have commit pr again, but the CI is failed too......

**Comment by tristaZero** [comment]
@xiyelife Sorry for that, i notified it to other colleagues. Besides, waiting for some time and trying again is always an appropriate option, you know. :)

**Comment by tristaZero** [comment]
Hi @xiyelife Thanks your contribution, i found #3770 is caused by another PR, therefore we decided to rollback the last PR to solve #3770 from the source.
@KomachiSion could you refer the problem PR to this one? After that, i willl close this PR. Again @xiyelife Thank you to remind us this issue. Hope see your interaction more in community. :)

**Comment by xiyelife** [comment]
@tristaZero All right，I see.

**Comment by tristaZero** [comment]
#3809 answears the related issue.

**Pull request closed without merging**
