### PR TITLE
enhancement 1285: sharding.jdbc.datasource.names support inline expir…

### LINKED ISSUE #1285: sharding.jdbc.datasource.names only support datasource names separated by comma
## Feature Request

**For English only**, other languages will not accept.

Please pay attention on issues you submitted, because we maybe need more details. 
If no response **more than 7 days** and we cannot make decision by current information, we will **close it**.

Please answer these questions before submitting your issue. Thanks!

### Is your feature request related to a problem?

No.

### Describe the feature you would like.

hope the sharding.jdbc.datasource.names in application.properties can support expression like ds,ds_${0..3}。
but， the SpringBootConfiguration show me that only support datasource names separated by comma. if tens of names， the conf is unfriendly at all.

### PR DESCRIPTION
**Pull request by feelwing1314**
…ession

Fixes #1285 .

Changes proposed in this pull request:
-
-
-

### CODE REVIEW

**Comment by terrymanu** [comment]
And 
all of inline parser is in sharding rule. 
I suggest we can move data sources' inline expresstion to sharding rule, and then all of config type can support well.

**Comment by tristaZero** [comment]
@feelwing1314 Hi, thanks for your pr. In my opinion, your pr is a great enhancement for sharding-spring-boot, but now sharding-spring is an independent sub-project as [sharding-spring](https://github.com/sharding-sphere/sharding-spring), so can you create a new pr for [sharding-spring](https://github.com/sharding-sphere/sharding-spring) with the detail of this pr?

In addtion, my suggestion for this pr are as follows:
*  Please extract a new function to get `dataSourceList`
*  Instead of creating `SpringBootShardingInlineTest` and `SpringBootMasterSlaveInlineTest`, can you move `assertWithShardingDataSource()` to `SpringBootShardingTest` and move `assertWithMasterSlaveDataSource()` to`SpringBootMasterSlaveTest`? Of cource, they need new function names.

**Comment by tristaZero** [comment]
@feelwing1314 Hi, is there any problem to make this pr available? If so, please contact me. 
Moreover, i do not know whether you are interested in another requirement presented by ShardingSphere community, which is related to this one, i.e, The Sharding configuration of springboot can support not only inline expression, but springboot placeholder, e.g, person.age=${random.int}.

Just do it in your own pace, welcome subscribe our [dev mail list](dev@shardingsphere.apache.org), so we can talk more.

**Comment by terrymanu** [comment]
finished by https://github.com/sharding-sphere/sharding-spring/pull/13

**Pull request closed without merging**
