### PR TITLE
Add new key generator "LeafSegmentKeyGenerator"  and related functions.

### LINKED ISSUE #1775: Leaf key generator implementation for Apache ShardingSphere
Modifying API of generating gobally unique ID, and providing alternatives of gobally unique ID generator for users now is ongoing.

To meet users' different needs and make the module of globally unique ID key generator more powerful, we plan to implement Leaf key generator for ShardingSphere.

Welcome [@Zhaodong Xie](https://github.com/Yaccc), the author of Leaf, to contribute to Apache ShardingSphere. He will be in charge of Leaf key generator implementation for Apache ShardingSphere.

[1] https://tech.meituan.com/MT_Leaf.html

### PR DESCRIPTION
**Pull request by wgy8283335**
Fixes #1775.

Changes proposed in this pull request:
- Add new key generator "LeafSegmentKeyGenerator"  and related functions.
-
-

### CODE REVIEW

**Comment by wgy8283335** [comment]
@terrymanu .
The test failed, due to LeafSegmentKeyGenrator test **depends on zookeeper.** Do u have any suggestion for me?
13:26:17.983 [pool-1-thread-1-SendThread(127.0.0.1:2181)] DEBUG org.apache.zookeeper.ClientCnxnSocketNIO - Ignoring exception during shutdown output
java.nio.channels.ClosedChannelException: null
	at sun.nio.ch.SocketChannelImpl.shutdownOutput(SocketChannelImpl.java:797)
	at sun.nio.ch.SocketAdaptor.shutdownOutput(SocketAdaptor.java:407)
	at org.apache.zookeeper.ClientCnxnSocketNIO.cleanup(ClientCnxnSocketNIO.java:207)
	at org.apache.zookeeper.ClientCnxn$SendThread.cleanup(ClientCnxn.java:1185)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1110)

**Comment by terrymanu** [comment]
You can try to use curator-test which can startup a zookeeper in memory, or use mock to do unit-test

**Comment by wgy8283335** [comment]
@terrymanu .THX, I will try it later.

**Comment by terrymanu** [comment]
Nice work, thank you.
Let @tristaZero to review it.

**Comment by tristaZero** [comment]
@wgy8283335 Thanks, i think it is great after a quick look.
I will give you feedback as soon sa possiable.

**Comment by wgy8283335** [comment]
@tristaZero. Thank you.

**Comment by tristaZero** [comment]
@wgy8283335 

After reading your pr carefully and digging into the Leaf-segement and Leaf-Snowflake, i give my opinions about this pr, and also want to have
a discuss in detail with you, please let me know your feedback. Thanks.


1.The package of sharding-core-common should be basic package which is used by other packages, so it is better to move all the classes related to LeafSegmentKeyGenerator to sharding-orchestration-core

2.When LeafSegmentKeyGenerator is in sharding-orchestration-core, maybe we can consider to use CuratorZookeeperRegistryCenter instead of LeafCuratorZookeeper. The function of incrementCacheId in LeafCuratorZookeeper can considered to move to LeafSegmentKeyGenerator, and moving tryLock() to CuratorZookeeperRegistryCenter is ok?

3.The API of generateKey() now is to return null in LeafSegmentKeyGenerator, but it is not allowed to modify APIs. Therefore using generateKey(), not generateKey(tableName) is a better choice.

4. Actually, LeafSegmentKeyGenerator really needs tableName as a key in zk. So i suggest set tableName in properties of LeafSegmentKeyGenerator and getTableName() from properties to use it in zk.

5.The another important thing is multiple schemas. If user use same tableName in multiple schemas, the node value of same table name in zk will be overwrite. So please consider use schemaName and tableName as note key.

**Pull request closed without merging**
