### PR TITLE
Solve the problem when project's default charset is not utf-8

### LINKED ISSUE #3810: When the default character code of my project is not UTF-8, decryption fails due to scrambling
When the default character code of my project is not UTF-8, decryption fails due to scrambling

### PR DESCRIPTION
**Pull request by minghu-zhang**
Fixes #3810.

Changes proposed in this pull request:
- modified：AESShardingEncryptor.java
-
-

### CODE REVIEW

**Comment by terrymanu** [comment]
How about if the original string is not UTF8?

**Comment by minghu-zhang** [comment]
> How about if the original string is not UTF8?

It will cause the result of decryption to be disorderly

**Comment by minghu-zhang** [comment]
> How about if the original string is not UTF8?

The encryption uses utf-8 encoding, but the decryption does not specify the encoding, and the default system encoding is used. When our system defaults encoding is GBK , the correct result cannot be obtained

**Comment by terrymanu** [comment]
Can `UTF8` solve all charset problems?
Do we need add a property key to let user provide the charset, just like `aes.key.value`?

**Pull request merged**
