### PR TITLE
Added additional Unit Tests to increase code coverage

### PR DESCRIPTION
**Pull request by TheRealHaui**
Added additional Unit Tests to increase code coverage.

### CODE REVIEW

**Comment by terrymanu** [comment]
Unfortunately, we just refactor the target class of this test case, which cause the new test cases compile failure. Could you just update new version and fix compile error?

Thank you very much.

**Comment by TheRealHaui** [comment]
@terrymanu,
no problem.

**Comment by terrymanu** [comment]
nice work, thank you

**Comment by TheRealHaui** [comment]
You are welcome!

**Pull request merged**
